name: pvade
channels:
  - conda-forge  
  - defaults
dependencies:
  # Dependencies should be kept as loosely pinned to version numbers as possible
  - alive-progress
  - black
  - fenics-dolfinx=0.6
  - jsonschema
  - jupyter
  - matplotlib
  - meshio
  - pandas
  - pytest
  - python-gmsh
  - pyyaml
  - scipy
  - snakeviz
  - sphinx
  - tqdm
  - pip
  - pip:
    - sphinx-rtd-theme
    - -e . # Installs the pvade package
