name: test_pvade

on:
  push:
    branches: [ main ]
    # branches: [ main, dev ]
  pull_request:
    branches: [ main, dev, sync]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1 of 2 - run pytest on code
  pytest:
    name: Pytest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: environment.yaml
      - name: Run pytest
        shell: bash -l {0}
        run: pytest -sv pvade/tests/

  # Job 2 of 2 - enforce Black formatting
  formatting:
    name: Black formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
